name: build

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: flashmark
          path: target/release/flashmark.exe
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/flashmark.exe
